ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "is_repeating" BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "repeat_period" VARCHAR(20) NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "repeat_interval" INTEGER DEFAULT 1 NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "repeat_end_date" TIMESTAMP NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "repeat_count" INTEGER NULL;
